### ISSUE TITLE
Pre-November Milestone work

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#94]
The work on this ticket is just to create the GUI skeleton for the November sprint work. 

This is a subset of the things to be done defined on #91.  The point of this ticket is that we need to create a few dropdown/menus on the current setup in order to fulfill the gui part of the interface/backend work in https://github.com/spacetelescope/cubeviz/milestone/1. 

Create Cube Processing Menu on CubeViz bar
- [ ] 2D Moment maps (#90)
- [ ] Basic arithmetic operations (#80)
- [ ] Button/menu for spatial smoothing ( #74)    
- [ ] Button/menu for generic apply function across spaxels ( #78 )

Spectral Menu Bar Range Dropdown 
- [ ] Select/cut/chop spectrum for further processing (#59, #93)
- [ ] Button/menu for spectral smoothing ( #74)  (maybe use smoothing button already there

Other
- [ ]  Display a vertical line in the spectrum showing the wavelength of the current image
- [ ] Cursor shows flux values, and RA/DEC for cursor location
- [x] Display the wavelength of the current image (#46)

Change "Advanced Options" text on button to "Viewer Options" (TBD the actual name)
reverse order of "Filter" menu items (arithmetic first). 

Need to determine who does what on Monday.  @kassin @nmearl @hcferguson

**Comment by drdavella** [comment]
@brechmos-stsci other notes of things we need to do: 
  * Move cube processing menu to new icon with menu dropdown
  * Move view menu to new icon with menu dropdown
  * Move the "flux/error/dq" dropdowns to the viewer menu bar
  * Linking of views (for slices and/or zooming/panning)
  * Label slice and wavelength (near slider)
  * Move "Advanced Options" to one menubar up and call it "Viewer Options" ( @astrofrog )
  * Make "cubeviz" command to auto startup like it does with "glue --startup=cubeviz" ( @astrofrog )

**Comment by brechmos-stsci** [comment]
@astrofrog There are two things you are tagged on for this pre-sprint stuff (see above comment).  How are those going?  Both would be great to have :-) This week @drdavella and I will look at the linking of views (Tues or Wed).

**Comment by astrofrog** [comment]
@brechmos-stsci - I'll work on these now :)

**Comment by astrofrog** [comment]
@brechmos-stsci - done in https://github.com/spacetelescope/cubeviz/pull/97 and https://github.com/spacetelescope/cubeviz/pull/98

**Comment by kassin** [comment]
Going to close this (@brechmos-stsci)
